using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace YarneAPIBack.Data;

public static class AccountingV2SchemaPatches
{
    private static int _tablesEnsured;

    public static async Task EnsureTablesAsync(
        YarneDbContext db,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (Interlocked.CompareExchange(ref _tablesEnsured, 1, 0) != 0)
            return;

        if (!db.Database.IsNpgsql())
            return;

        try
        {
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "Material" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(255) NOT NULL,
                    "Description" character varying(1000) NULL,
                    "Unit" character varying(50) NOT NULL DEFAULT 'pcs',
                    "Sku" character varying(100) NULL,
                    "IsActive" boolean NOT NULL DEFAULT true,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "PK_Material" PRIMARY KEY ("Id")
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Material_Name"
                    ON "Material" ("Name");

                CREATE INDEX IF NOT EXISTS "IX_Material_Sku"
                    ON "Material" ("Sku");

                CREATE TABLE IF NOT EXISTS "ImportTransaction" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Supplier" character varying(255) NULL,
                    "TransactionDate" timestamp with time zone NOT NULL,
                    "ReceivedDate" timestamp with time zone NULL,
                    "Notes" character varying(1000) NULL,
                    "InvoiceRef" character varying(150) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "PK_ImportTransaction" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_ImportTransaction_TransactionDate"
                    ON "ImportTransaction" ("TransactionDate");

                CREATE TABLE IF NOT EXISTS "ImportTransactionLine" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ImportTransactionId" integer NOT NULL,
                    "MaterialId" integer NOT NULL,
                    "Quantity" numeric(18,4) NOT NULL,
                    "UnitPrice" numeric(18,2) NOT NULL,
                    CONSTRAINT "PK_ImportTransactionLine" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_ImportTransactionLine_ImportTransaction_ImportTransactionId"
                        FOREIGN KEY ("ImportTransactionId") REFERENCES "ImportTransaction" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_ImportTransactionLine_Material_MaterialId"
                        FOREIGN KEY ("MaterialId") REFERENCES "Material" ("Id") ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS "IX_ImportTransactionLine_ImportTransactionId"
                    ON "ImportTransactionLine" ("ImportTransactionId");

                CREATE INDEX IF NOT EXISTS "IX_ImportTransactionLine_MaterialId"
                    ON "ImportTransactionLine" ("MaterialId");

                CREATE TABLE IF NOT EXISTS "Expense" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Category" character varying(100) NOT NULL,
                    "Name" character varying(255) NOT NULL,
                    "Description" character varying(1000) NULL,
                    "Amount" numeric(18,2) NOT NULL,
                    "ExpenseDate" timestamp with time zone NOT NULL,
                    "Notes" character varying(1000) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "PK_Expense" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_Expense_Category"
                    ON "Expense" ("Category");

                CREATE INDEX IF NOT EXISTS "IX_Expense_ExpenseDate"
                    ON "Expense" ("ExpenseDate");

                CREATE TABLE IF NOT EXISTS "MaterialUsageRecord" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "MaterialId" integer NOT NULL,
                    "OrderId" integer NULL,
                    "QuantityUsed" numeric(18,4) NOT NULL,
                    "UsageDate" timestamp with time zone NOT NULL,
                    "Notes" character varying(1000) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "PK_MaterialUsageRecord" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_MaterialUsageRecord_Material_MaterialId"
                        FOREIGN KEY ("MaterialId") REFERENCES "Material" ("Id") ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS "IX_MaterialUsageRecord_MaterialId"
                    ON "MaterialUsageRecord" ("MaterialId");

                CREATE INDEX IF NOT EXISTS "IX_MaterialUsageRecord_OrderId"
                    ON "MaterialUsageRecord" ("OrderId");

                CREATE INDEX IF NOT EXISTS "IX_MaterialUsageRecord_UsageDate"
                    ON "MaterialUsageRecord" ("UsageDate");

                CREATE TABLE IF NOT EXISTS "StockReport" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "SnapshotDate" timestamp with time zone NOT NULL,
                    "Label" character varying(255) NULL,
                    "Notes" character varying(1000) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    "IsLocked" boolean NOT NULL DEFAULT true,
                    CONSTRAINT "PK_StockReport" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_StockReport_SnapshotDate"
                    ON "StockReport" ("SnapshotDate");

                CREATE TABLE IF NOT EXISTS "StockReportLine" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "StockReportId" integer NOT NULL,
                    "MaterialId" integer NOT NULL,
                    "MaterialName" character varying(255) NOT NULL,
                    "MaterialUnit" character varying(50) NOT NULL,
                    "QtyImported" numeric(18,4) NOT NULL,
                    "QtyUsed" numeric(18,4) NOT NULL,
                    "QtyOnHand" numeric(18,4) NOT NULL,
                    "AvgUnitCost" numeric(18,2) NOT NULL,
                    "TotalValue" numeric(18,2) NOT NULL,
                    CONSTRAINT "PK_StockReportLine" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_StockReportLine_StockReport_StockReportId"
                        FOREIGN KEY ("StockReportId") REFERENCES "StockReport" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_StockReportLine_StockReportId"
                    ON "StockReportLine" ("StockReportId");

                CREATE INDEX IF NOT EXISTS "IX_StockReportLine_MaterialId"
                    ON "StockReportLine" ("MaterialId");
                """,
                cancellationToken);

            logger.LogInformation("Verified accounting V2 tables exist.");
        }
        catch (Exception ex)
        {
            Interlocked.Exchange(ref _tablesEnsured, 0);
            logger.LogError(ex, "Failed to ensure accounting V2 tables.");
            throw;
        }
    }
}
