using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace YarneAPIBack.Data;

public static class AccountingEnhancementsSchemaPatches
{
    private static int _ensured;

    public static async Task EnsureAsync(
        YarneDbContext db,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (Interlocked.CompareExchange(ref _ensured, 1, 0) != 0)
            return;

        if (!db.Database.IsNpgsql())
            return;

        try
        {
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "ImportTransaction"
                    ADD COLUMN IF NOT EXISTS "IsLocked" boolean NOT NULL DEFAULT false;

                CREATE TABLE IF NOT EXISTS "ExpenseCategory" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(100) NOT NULL,
                    "Description" character varying(500) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "PK_ExpenseCategory" PRIMARY KEY ("Id")
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_ExpenseCategory_Name"
                    ON "ExpenseCategory" ("Name");

                CREATE TABLE IF NOT EXISTS "ExternalOrder" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Label" character varying(255) NULL,
                    "CustomerName" character varying(255) NULL,
                    "OrderDate" timestamp with time zone NOT NULL,
                    "Notes" character varying(1000) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "PK_ExternalOrder" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_ExternalOrder_OrderDate"
                    ON "ExternalOrder" ("OrderDate");

                ALTER TABLE "MaterialUsageRecord"
                    ADD COLUMN IF NOT EXISTS "ExternalOrderId" integer NULL;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_MaterialUsageRecord_ExternalOrder_ExternalOrderId'
                    ) THEN
                        ALTER TABLE "MaterialUsageRecord"
                            ADD CONSTRAINT "FK_MaterialUsageRecord_ExternalOrder_ExternalOrderId"
                            FOREIGN KEY ("ExternalOrderId") REFERENCES "ExternalOrder" ("Id") ON DELETE SET NULL;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS "IX_MaterialUsageRecord_ExternalOrderId"
                    ON "MaterialUsageRecord" ("ExternalOrderId");

                INSERT INTO "ExpenseCategory" ("Name", "Description", "CreatedAt")
                SELECT v.name, v.description, CURRENT_TIMESTAMP
                FROM (VALUES
                    ('Marketing', 'Ads, promotions, influencers'),
                    ('Utilities', 'Electricity, rent, internet'),
                    ('Operations', 'General business operations'),
                    ('Shipping', 'Delivery and logistics'),
                    ('Other', 'Miscellaneous expenses')
                ) AS v(name, description)
                WHERE NOT EXISTS (SELECT 1 FROM "ExpenseCategory" LIMIT 1);
                """,
                cancellationToken);

            logger.LogInformation("Verified accounting enhancement schema.");
        }
        catch (Exception ex)
        {
            Interlocked.Exchange(ref _ensured, 0);
            logger.LogError(ex, "Failed to ensure accounting enhancement schema.");
            throw;
        }
    }
}
