using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace YarneAPIBack.Data;

public static class AccountingSchemaPatches
{
    private static int _tablesEnsured;

    public static async Task EnsureTablesAsync(
        YarneDbContext db,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (Interlocked.CompareExchange(ref _tablesEnsured, 1, 0) != 0)
            return;

        if (!db.Database.IsNpgsql())
            return;

        try
        {
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "AccountingCategory" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(150) NOT NULL,
                    "Description" character varying(500) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "PK_AccountingCategory" PRIMARY KEY ("Id")
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_AccountingCategory_Name"
                    ON "AccountingCategory" ("Name");

                CREATE TABLE IF NOT EXISTS "MarketingExpenditure" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(255) NOT NULL,
                    "Description" character varying(1000) NULL,
                    "Amount" numeric(18,2) NOT NULL,
                    "ExpenseDate" timestamp with time zone NOT NULL,
                    "Notes" character varying(1000) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "PK_MarketingExpenditure" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_MarketingExpenditure_ExpenseDate"
                    ON "MarketingExpenditure" ("ExpenseDate");

                CREATE TABLE IF NOT EXISTS "AccountingPurchase" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CategoryId" integer NOT NULL,
                    "Name" character varying(255) NOT NULL,
                    "Description" character varying(1000) NULL,
                    "Supplier" character varying(255) NULL,
                    "PurchaseDate" timestamp with time zone NOT NULL,
                    "ReceivedDate" timestamp with time zone NULL,
                    "SoldDate" timestamp with time zone NULL,
                    "Quantity" integer NOT NULL,
                    "QuantitySold" integer NOT NULL,
                    "UnitCost" numeric(18,2) NOT NULL,
                    "SaleUnitPrice" numeric(18,2) NULL,
                    "Notes" character varying(1000) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "PK_AccountingPurchase" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_AccountingPurchase_AccountingCategory_CategoryId"
                        FOREIGN KEY ("CategoryId") REFERENCES "AccountingCategory" ("Id") ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS "IX_AccountingPurchase_CategoryId"
                    ON "AccountingPurchase" ("CategoryId");

                CREATE INDEX IF NOT EXISTS "IX_AccountingPurchase_PurchaseDate"
                    ON "AccountingPurchase" ("PurchaseDate");
                """,
                cancellationToken);
            logger.LogInformation("Verified accounting tables exist.");
        }
        catch (Exception ex)
        {
            Interlocked.Exchange(ref _tablesEnsured, 0);
            logger.LogError(ex, "Failed to ensure accounting tables.");
            throw;
        }
    }
}
