using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace YarneAPIBack.Data;

/// <summary>
/// Everything the order flow added to the database since October 2026 (tracking, payment, foreign
/// delivery, euro payment, making-of photos), as one statement that is safe to run on every start.
/// The EF migrations for these exist too, but a failed migration is swallowed at bootstrap and the
/// app then serves with columns missing, which breaks every order query. This guarantees the shape
/// regardless; the migrations use the same IF NOT EXISTS form, so either may run first.
/// </summary>
public static class OrderFlowSchemaPatches
{
    internal const string EnsureSql =
        """
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "CancelReason" character varying(500) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "IsForeignDelivery" boolean NOT NULL DEFAULT FALSE;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "OrderNumber" character varying(16) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "PaymentChoice" character varying(16) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "PaymentChoiceAt" timestamp with time zone NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "StatusToken" character varying(64) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "DeliveryAddress" character varying(500) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "DeliveryCarrier" character varying(16) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "DeliveryCountryCode" character varying(2) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "DeliveryCountryName" character varying(100) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "DeliveryPostalCode" character varying(20) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "FinalizedAt" timestamp with time zone NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "PaymentReceivedAt" timestamp with time zone NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "ReceiptContentType" character varying(50) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "ReceiptKey" character varying(200) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "ReceiptUploadedAt" timestamp with time zone NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "PaymentClaimedAt" timestamp with time zone NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "PaymentCurrency" character varying(3) NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "EurTotalCents" bigint NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "PhotosRequestedAt" timestamp with time zone NULL;
        ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "PhotosNotifiedAt" timestamp with time zone NULL;

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Order_OrderNumber" ON "Order" ("OrderNumber");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Order_StatusToken" ON "Order" ("StatusToken");

        CREATE TABLE IF NOT EXISTS "OrderMakingPhoto" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "OrderId" integer NOT NULL,
            "StorageKey" character varying(200) NOT NULL,
            "ContentType" character varying(50) NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            CONSTRAINT "PK_OrderMakingPhoto" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_OrderMakingPhoto_Order_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Order" ("Id") ON DELETE CASCADE
        );
        CREATE INDEX IF NOT EXISTS "IX_OrderMakingPhoto_OrderId" ON "OrderMakingPhoto" ("OrderId");
        """;

    public static async Task ForceEnsureAsync(YarneDbContext db, ILogger logger, CancellationToken cancellationToken = default)
    {
        if (!db.Database.IsNpgsql())
            return;

        await db.Database.ExecuteSqlRawAsync(EnsureSql, cancellationToken);
        logger.LogInformation("Order flow schema ensured (tracking, payment, foreign delivery, euro, making-of photos).");
    }
}
