using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace YarneAPIBack.Data;

/// <summary>
/// The PasswordResetToken table as one statement that is safe to run on every start. The EF migration uses the same
/// IF NOT EXISTS form, so either may run first; a failed migration is swallowed at bootstrap, this is the safety net.
/// </summary>
public static class PasswordResetSchemaPatches
{
    internal const string EnsureSql =
        """
        CREATE TABLE IF NOT EXISTS "PasswordResetToken" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "CustomerId" integer NOT NULL,
            "TokenHash" character varying(128) NOT NULL,
            "ExpiresAt" timestamp with time zone NOT NULL,
            "UsedAt" timestamp with time zone NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            CONSTRAINT "PK_PasswordResetToken" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_PasswordResetToken_Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customer" ("Id") ON DELETE CASCADE
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_PasswordResetToken_TokenHash" ON "PasswordResetToken" ("TokenHash");
        CREATE INDEX IF NOT EXISTS "IX_PasswordResetToken_CustomerId" ON "PasswordResetToken" ("CustomerId");
        """;

    public static async Task ForceEnsureAsync(YarneDbContext db, ILogger logger, CancellationToken cancellationToken = default)
    {
        if (!db.Database.IsNpgsql())
            return;

        await db.Database.ExecuteSqlRawAsync(EnsureSql, cancellationToken);
        logger.LogInformation("Password reset schema ensured.");
    }
}
