using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace YarneAPIBack.Data;

public static class RefreshTokenSchemaPatches
{
    private static int _tablesEnsured;

    public static async Task EnsureTablesAsync(
        YarneDbContext db,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (Interlocked.CompareExchange(ref _tablesEnsured, 1, 0) != 0)
            return;

        try
        {
            await ForceEnsureAsync(db, logger, cancellationToken);
        }
        catch (Exception ex)
        {
            Interlocked.Exchange(ref _tablesEnsured, 0);
            logger.LogError(ex, "RefreshToken schema ensure failed during migrations path; will retry via bootstrap ForceEnsure.");
        }
    }

    /// <summary>Always attempt RefreshToken DDL. Safe to call repeatedly.</summary>
    public static async Task ForceEnsureAsync(
        YarneDbContext db,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (!db.Database.IsNpgsql())
            return;

        // Create table + indexes first (critical for login). Self-FK is optional.
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "RefreshToken" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "CustomerId" integer NOT NULL,
                "TokenHash" character varying(128) NOT NULL,
                "ExpiresAtUtc" timestamp with time zone NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "RevokedAtUtc" timestamp with time zone NULL,
                "ReplacedByTokenId" integer NULL,
                CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_RefreshToken_Customer_CustomerId"
                    FOREIGN KEY ("CustomerId") REFERENCES "Customer" ("Id") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshToken_TokenHash"
                ON "RefreshToken" ("TokenHash");

            CREATE INDEX IF NOT EXISTS "IX_RefreshToken_CustomerId"
                ON "RefreshToken" ("CustomerId");

            CREATE INDEX IF NOT EXISTS "IX_RefreshToken_ExpiresAtUtc"
                ON "RefreshToken" ("ExpiresAtUtc");
            """,
            cancellationToken);

        try
        {
            await db.Database.ExecuteSqlRawAsync(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_RefreshToken_RefreshToken_ReplacedByTokenId'
                    ) THEN
                        ALTER TABLE "RefreshToken"
                            ADD CONSTRAINT "FK_RefreshToken_RefreshToken_ReplacedByTokenId"
                            FOREIGN KEY ("ReplacedByTokenId") REFERENCES "RefreshToken" ("Id")
                            ON DELETE SET NULL;
                    END IF;
                END $$;
                """,
                cancellationToken);
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "RefreshToken self-FK could not be applied; table itself is usable.");
        }

        Interlocked.Exchange(ref _tablesEnsured, 1);
        logger.LogInformation("Verified RefreshToken table exists.");
    }
}
