using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace YarneAPIBack.Data;

/// <summary>
/// Idempotent self-heal for the sale-time composition schema (lace/packaging):
/// Product.IsInternalComponent, OrderItem.ParentOrderItemId (+ FK), and the
/// ProductSaleComponent table. Mirrors the ADD COLUMN IF NOT EXISTS pattern used
/// elsewhere so a partially-migrated production DB recovers on boot.
/// </summary>
public static class SaleComponentSchemaPatches
{
    private static int _ensured;

    private const string EnsureSql =
        """
        DO $$
        BEGIN
            ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "IsInternalComponent" boolean NOT NULL DEFAULT false;
            ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "ParentOrderItemId" integer NULL;

            -- Guard by column, not by name: the EF migration names this FK
            -- "FK_OrderItem_OrderItem_ParentOrderItemId"; only add ours if no FK on the
            -- ParentOrderItemId column exists yet (avoids a duplicate self-FK).
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.table_constraints AS tc
                JOIN information_schema.key_column_usage AS kcu
                  ON tc.constraint_name = kcu.constraint_name
                 AND tc.table_schema = kcu.table_schema
                WHERE tc.constraint_type = 'FOREIGN KEY'
                  AND tc.table_schema = 'public'
                  AND tc.table_name = 'OrderItem'
                  AND kcu.column_name = 'ParentOrderItemId'
            ) THEN
                ALTER TABLE "OrderItem"
                    ADD CONSTRAINT "FK_OrderItem_ParentOrderItem"
                    FOREIGN KEY ("ParentOrderItemId") REFERENCES "OrderItem" ("Id") ON DELETE NO ACTION;
            END IF;

            CREATE INDEX IF NOT EXISTS "IX_OrderItem_ParentOrderItemId"
                ON "OrderItem" ("ParentOrderItemId");

            CREATE TABLE IF NOT EXISTS "ProductSaleComponent" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProductId" integer NOT NULL,
                "ComponentProductId" integer NOT NULL,
                "Quantity" integer NOT NULL DEFAULT 1,
                "Condition" character varying(20) NOT NULL DEFAULT 'with_lace',
                "IsVoid" boolean NOT NULL DEFAULT false,
                "CreatedBy" integer NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "PK_ProductSaleComponent" PRIMARY KEY ("Id"),
                CONSTRAINT "CK_ProductSaleComponent_Quantity_Positive" CHECK ("Quantity" > 0),
                CONSTRAINT "FK_ProductSaleComponent_Product_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Product" ("Id") ON DELETE NO ACTION,
                CONSTRAINT "FK_ProductSaleComponent_Product_ComponentProductId"
                    FOREIGN KEY ("ComponentProductId") REFERENCES "Product" ("Id") ON DELETE NO ACTION
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductSaleComponent_ProductId_ComponentProductId_Condition"
                ON "ProductSaleComponent" ("ProductId", "ComponentProductId", "Condition")
                WHERE "IsVoid" = false;

            CREATE INDEX IF NOT EXISTS "IX_ProductSaleComponent_ComponentProductId"
                ON "ProductSaleComponent" ("ComponentProductId");

            CREATE INDEX IF NOT EXISTS "IX_ProductSaleComponent_CreatedBy"
                ON "ProductSaleComponent" ("CreatedBy");

            -- Per-color lace choice: which Color (shared with bag colors) a "with_lace" row
            -- represents. Null for "always" (packaging) rows and legacy un-migrated rows.
            ALTER TABLE "ProductSaleComponent" ADD COLUMN IF NOT EXISTS "ColorId" integer NULL;

            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.table_constraints AS tc
                JOIN information_schema.key_column_usage AS kcu
                  ON tc.constraint_name = kcu.constraint_name
                 AND tc.table_schema = kcu.table_schema
                WHERE tc.constraint_type = 'FOREIGN KEY'
                  AND tc.table_schema = 'public'
                  AND tc.table_name = 'ProductSaleComponent'
                  AND kcu.column_name = 'ColorId'
            ) THEN
                ALTER TABLE "ProductSaleComponent"
                    ADD CONSTRAINT "FK_ProductSaleComponent_Color_ColorId"
                    FOREIGN KEY ("ColorId") REFERENCES "Color" ("Id") ON DELETE NO ACTION;
            END IF;

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductSaleComponent_ProductId_Condition_ColorId"
                ON "ProductSaleComponent" ("ProductId", "Condition", "ColorId")
                WHERE "IsVoid" = false;

            CREATE INDEX IF NOT EXISTS "IX_ProductSaleComponent_ColorId"
                ON "ProductSaleComponent" ("ColorId");
        END $$;
        """;

    public static async Task ForceEnsureAsync(
        YarneDbContext db,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (!db.Database.IsNpgsql())
            return;

        await db.Database.ExecuteSqlRawAsync(EnsureSql, cancellationToken);
        Interlocked.Exchange(ref _ensured, 1);
        logger.LogInformation(
            "Verified sale-component schema (Product.IsInternalComponent, OrderItem.ParentOrderItemId, ProductSaleComponent).");
    }

    public static async Task EnsureAsync(
        YarneDbContext db,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (Interlocked.CompareExchange(ref _ensured, 1, 0) != 0)
            return;

        try
        {
            await ForceEnsureAsync(db, logger, cancellationToken);
        }
        catch (Exception ex)
        {
            Interlocked.Exchange(ref _ensured, 0);
            logger.LogError(ex, "SaleComponent schema ensure failed; will retry via bootstrap.");
        }
    }
}
